### ISSUE TITLE
paas服务运行失败 KeyError: 255

### ISSUE THREAD

**Issue by hzde0128** [Tencent/bk-PaaS#181]
环境：
python -V
Python 2.7.16

cat /etc/centos-release
CentOS Linux release 8.1.1911 (Core)

下面是运行login时的错误信息：
(venv) [vagrant@node01 login]$ python manage.py makemigrations
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
Migrations for 'bkaccount':
  0010_auto_20200414_0142.py:
    - Alter field code on bkrole
    - Alter field time_zone on userinfo

(venv) [vagrant@node01 login]$ python manage.py migrate
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/data/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/data/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/data/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/data/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/data/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/data/venv/lib/python2.7/site-packages/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/data/venv/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/data/venv/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/data/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 162, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/data/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/data/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/data/venv/lib/python2.7/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/data/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/data/venv/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/data/venv/lib/python2.7/site-packages/pymysql/connections.py", line 657, in __init__
    self.connect()
  File "/data/venv/lib/python2.7/site-packages/pymysql/connections.py", line 850, in connect
    self._get_server_information()
  File "/data/venv/lib/python2.7/site-packages/pymysql/connections.py", line 1085, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/data/venv/lib/python2.7/site-packages/pymysql/charset.py", line 34, in by_id
    return self._by_id[id]
KeyError: 255

**Comment by wklken** [comment]
https://segmentfault.com/a/1190000016628000

使用的MySQL 8.0? 
升级pymysql或者使用MySQL 5.X

**Comment by hzde0128** [comment]
是的，执行`pip install pymysql -U` 升级到最新版本后可以了

**Comment by wklken** [comment]
ok
