### ISSUE TITLE
paas部署后登陆报错

### ISSUE THREAD

**Issue by FengZh61** [Tencent/bk-PaaS#707]
我按照部署文档安装了bk-PaaS-5.2，在登陆http://www.bking.com:8001/时出现以下报错

[24/Jan/2022 16:01:32] "GET /login/?c_url=http%3A//www.bking.com%3A8001/ HTTP/1.1" 200 24274
[24/Jan/2022 16:01:32] "GET /jsi18n/i18n/ HTTP/1.1" 200 2486
ERROR Internal Server Error: /login/ 
Traceback (most recent call last):
  File "/opt/bk_pass/login/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bk_pass/login/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/bk_pass/login/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/decorators.py", line 20, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/bk_pass/login/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/common/mixins/exempt.py", line 33, in dispatch
    return super(LoginExemptMixin, self).dispatch(*args, **kwargs)
  File "/opt/bk_pass/login/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/views.py", line 47, in post
    return self._login(request)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/views.py", line 38, in _login
    return account.login(request)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/accounts.py", line 244, in login
    return self.login_success_response(request, form, redirect_to, app_id)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/accounts.py", line 325, in login_success_response
    bk_token, expire_time = self.get_bk_token(username)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/accounts.py", line 112, in get_bk_token
    bk_token = encrypt(plain_token)
  File "/opt/bk-PaaS-5.2/paas-ce/paas/login/bkaccount/encryption.py", line 64, in encrypt
    ciphertext = cipher.encrypt(pad(plaintext))
  File "/opt/bk_pass/login/lib64/python2.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 136, in encrypt
    c_uint8_ptr(plaintext),
  File "/opt/bk_pass/login/lib64/python2.7/site-packages/Crypto/Util/_raw_api.py", line 242, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <type 'unicode'> cannot be passed to C code
[24/Jan/2022 16:01:36] "POST /login/?c_url=http%3A//www.bking.com%3A8001/ HTTP/1.1" 500 156263
[24/Jan/2022 16:01:36] "GET /favicon.ico HTTP/1.1" 404 3721
![捕获](https://user-images.githubusercontent.com/98309003/150744218-b08b09cc-8991-4dc3-80b0-6901ceaade44.PNG)

我是在哪里的配置出现问题了吗？
我在部署python2.7.5的虚拟环境时忽略了uWSGI==2.0.13.1依赖，pycrypto用的是pycryptodome，因为我在按照requirements.txt中的依赖时这两个报错了。

**Comment by wklken** [comment]
应该是 pycryptodome 导致的原先依赖 pycrypto 的函数调用报错

```
File "/opt/bk_pass/login/lib64/python2.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 136, in encrypt
c_uint8_ptr(plaintext),
File "/opt/bk_pass/login/lib64/python2.7/site-packages/Crypto/Util/_raw_api.py", line 242, in c_uint8_ptr
raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <type 'unicode'> cannot be passed to C code
```

-----

请使用requirements.txt中依赖的 pycrypto. 安装时如果报错, 解决相关报错问题(具体根据报错信息确定问题, 搜索相关解决方案, 大多时编译失败), 确保正确能装上 pycrypto

**Comment by FengZh61** [comment]
> 应该是 pycryptodome 导致的原先依赖 pycrypto 的函数调用报错
> 
> ```
> File "/opt/bk_pass/login/lib64/python2.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 136, in encrypt
> c_uint8_ptr(plaintext),
> File "/opt/bk_pass/login/lib64/python2.7/site-packages/Crypto/Util/_raw_api.py", line 242, in c_uint8_ptr
> raise TypeError("Object type %s cannot be passed to C code" % type(data))
> TypeError: Object type <type 'unicode'> cannot be passed to C code
> ```
> 
> 请使用requirements.txt中依赖的 pycrypto. 安装时如果报错, 解决相关报错问题(具体根据报错信息确定问题, 搜索相关解决方案, 大多时编译失败), 确保正确能装上 pycrypto

感谢解答，已解决这个报错，我用python virtualenv安装pycrypto一直报错，后来改用miniconda搭建环境，安装依赖，都已解决，其中uWSGI被忽略了，我在其他issue看到解答是可以不用安装的。

**Comment by wklken** [comment]
可以使用gunicorn启动(最近的版本都全部切换使用gunicorn)
