### ISSUE TITLE
执行 python manage.py migrate报错

### ISSUE THREAD

**Issue by tanghulu9312** [Tencent/bk-PaaS#864]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG REPORT

**PaaS/PaaSAgent版本(The versions used):**
PAAS版本:2.14.3

**发生了什么(What happened):**
以下是执行 python manage.py migrate
root@localhost:/data/bk-PaaS-2.14.3/paas2/paas# python manage.py migrate

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**
 python manage.py migrate

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/bk-PaaS-2.14.3/paas2/paas/urls.py", line 28, in <module>
    url(r"^accounts/", include("account.urls")),
  File "/usr/local/lib/python2.7/dist-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/bk-PaaS-2.14.3/paas2/paas/account/urls.py", line 16, in <module>
    from account import views, profile_views
  File "/data/bk-PaaS-2.14.3/paas2/paas/account/profile_views.py", line 23, in <module>
    from components import usermgr
  File "/data/bk-PaaS-2.14.3/paas2/paas/components/usermgr.py", line 14, in <module>
    from components import usermgr_api
  File "/data/bk-PaaS-2.14.3/paas2/paas/components/usermgr_api.py", line 15, in <module>
    from .http import http_post
  File "/data/bk-PaaS-2.14.3/paas2/paas/components/http.py", line 90
    f"status_code is {resp.status_code}, not 200! "
                                                  ^
SyntaxError: invalid syntax

**备注(Anything else we need to know):** 
Python版本2.7.17
系统：Ubuntu18.04.02

**Comment by wklken** [comment]
2.14.3 是python3版本, 需要使用`python3`

2.13.x 及之前的版本是python2
