### ISSUE TITLE
PaaS 平台 esb组件缺少配置文件

### ISSUE THREAD

**Issue by kevinwuqingming** [Tencent/bk-PaaS#910]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):BUG REPORT

**PaaS/PaaSAgent版本(The versions used):**bk-PaaS-2.12.49

**发生了什么(What happened):esb组件缺少配置文件paas2/esb/conf/settings_development.py

**期望是什么(What you expected to happen):文件补充完整

**如何复现(How to reproduce it):查看代码文件可复现

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):
[root@bking esb]# python manage.py runserver 8002
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/bk-PaaS-2.12.49/paas2/esb/settings.py", line 32, in <module>
    raise ImportError("Could not import conf '%s' (Is it on sys.path?): %s" % (conf_module, e))
ImportError: Could not import conf 'conf.settings_development' (Is it on sys.path?): No module named settings_development

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
代码库中缺少 settings_development.py, 本地开发时, 需要手工加一个
